### ISSUE TITLE
Project not building for me

### ISSUE THREAD

**Issue by andrew2241** [Lombiq/Open-Source-Orchard-Core-Extensions#1]
I cannot seem to get the project to build. I get an error "The command "gulp" exited with code 9009" for both the VueJs and TrainingDemo projects. Could you possibly steer me in the right direction to get this to build?

**Comment by Piedone** [comment]
I think this is due to the lack of gulp installation. If you don't have it installed follow these steps:


1. Make sure that you have the latest LTS version of Node.js installed that fits your system architecture (x64 or x86).
2. Install or update NPM to the latest version using the command: npm install -g npm@latest
3. nstall or update the Gulp CLI globally with this command: npm install -g gulp-cli
4. Close Visual Studio, purge (hg purge) or cleanup (git clean -fxd) the repository and clear your NPM cache (npm cache clean -f). Note that hg purge is not recursive and won't touch subrepos! You need to purge those one by one.
5. Start Visual Studio and select the manually installed version of NodeJS as the default one used by Visual Studio to make sure that it's using the version that you'd use from command line (since the path to node.exe is automatically added to the PATH environment variable upon installation). Not having this set up can cause problems if a certain package needs resources for a certain processor architecture: VS is 32-bit, so some assets may be missing if your system is 64-bit.
   - In Visual Studio, hit Ctrl+Q, type "External Web Tools" and open the matching settings page (VS 2019 might not find it right away, but then you can open it from under Tools → Options → Projects and Solutions → Web Package Management.
   - Add the installation path of Node.js (most possibly "C:\Program Files\NodeJS") to the list and move it to the top.

**Comment by andrew2241** [comment]
Thank you, from your message I figured it out. I had installed gulp from an elevated command prompt. When running Visual Studio from my regular user account it could not utilize gulp.  Thank you very much for your help.

**Comment by Piedone** [comment]
Glad to hear Andrew!
