### ISSUE TITLE
Let's use Central Package Management to simplify NuGet package updates (OSOE-567)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/Open-Source-Orchard-Core-Extensions#401]
With NuGet 6.2, [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) can provide a much improved experience to manage NuGet packages over many project in a solution (folder).

The feature is available across all NuGet integrated tooling from the following versions:

    [Visual Studio 2022 17.2 and later](https://visualstudio.microsoft.com/downloads/)
    [.NET SDK 6.0.300 and later](https://dotnet.microsoft.com/download/dotnet/6.0)
    [.NET SDK 7.0.0-preview.4 and later](https://dotnet.microsoft.com/download/dotnet/7.0)
    [nuget.exe 6.2.0 and later](https://www.nuget.org/downloads)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-567)

**Comment by sarahelsaig** [comment]
Won't that be a hassle with submodules? Every project using them would have to implement its own Directory.Packages.props file. Also how would that work during NuGet publishing?

**Comment by Piedone** [comment]
We tried centrally managing OC dependencies before, though not this with feature, just by adding the same dependencies to all projects with a props file. It wasn't worth it.

Due to what Dávid says, I don't think this would work at all with OSOCE projects. In other projects, I don't really see the benefit: It'd make managing project-level dependencies more complicated, and at most what we gain is removing duplication of `Version` attributes, but only that we get rid of a bit of XML. Otherwise, due to enforced consolidation during builds, we already use common versions of each dependency.

**Comment by 0liver** [comment]
Both of you have good arguments. I guess I was somewhat blinded by the ✨ of this new, great feature, which it is for single-repo solutions.
