### ISSUE TITLE
Test Visual Studio build acceleration (OSOE-584)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#423]
Test if we can use [build acceleration](https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md) for the full solution, and if it indeed helps with build times.

- Elaborate results.
- Enable it for the full solution if it indeed works.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-584)

**Comment by DemeSzabolcs** [comment]
I haven't noticed any **significant** change in build time (I updated VS to 17.5, that supports this feature). I also tested it on the CI but no differences.

For OSOCE the build time on the output window was around 3 minutes for me every time (full rebuild). However, with build acceleration, I think sub-3-minute runs were more frequent (around 2:40-2:30) but maybe it's just a placebo.

I read if the project is well-optimized, then there could be no changes in build time after turning this on. Regardless of this, I have read that it's a good idea to keep it enabled. In some rare cases where the build is heavily customized, it can break things, [that's why it's not on by default everywhere](https://twitter.com/drewnoakes/status/1619435801435312128) (though it might be the default one day). For us, it's not causing any problems, so there are no downsides turning it on.

There was a tool that might show us some differences, but unfortunately, it's not ported to VS 2022. https://marketplace.visualstudio.com/items?itemName=OdysseasPetrocheilos.VisualStudioBuildTimer

**Comment by Piedone** [comment]
Build acceleration is only useful in repeated builds after you make some changes, not with full rebuilds.

**Comment by DemeSzabolcs** [comment]
I see.

I tested it that way too. I made 3 simple changes in 3 different projects within OSOCE. I did some builds with and without build acceleration (not a rebuild just a build) and the time was around 30-29 seconds every time. So no change in build time.

**Comment by Piedone** [comment]
Well, that's sad. Let's leave it turned on, then, since it's not breaking anything but there's a chance it can sometimes make things faster. Please link this issue in the code though, and briefly mention the results you've seen.
